// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyaeSbEzsbJGoLdDGZV3iK7UFphtiisg0',
    appId: '1:908766428964:web:4c3d6c784d0f5ec42b7db1',
    messagingSenderId: '908766428964',
    projectId: 'flutterwithfirebase-4a869',
    authDomain: 'flutterwithfirebase-4a869.firebaseapp.com',
    storageBucket: 'flutterwithfirebase-4a869.appspot.com',
    measurementId: 'G-81M73875GX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBerGlv8EJE7MmA7geFXmuyVl2dyLejh9k',
    appId: '1:908766428964:android:aa8216167de445572b7db1',
    messagingSenderId: '908766428964',
    projectId: 'flutterwithfirebase-4a869',
    storageBucket: 'flutterwithfirebase-4a869.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvKTaPd-8cZtO1wxnn67I424l7CV9BtC0',
    appId: '1:908766428964:ios:b037fa93adb2a6d12b7db1',
    messagingSenderId: '908766428964',
    projectId: 'flutterwithfirebase-4a869',
    storageBucket: 'flutterwithfirebase-4a869.appspot.com',
    iosClientId: '908766428964-9t9po31un97tv44hp28md65he6kg86c4.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterwithfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvKTaPd-8cZtO1wxnn67I424l7CV9BtC0',
    appId: '1:908766428964:ios:0d8939bf4151e4122b7db1',
    messagingSenderId: '908766428964',
    projectId: 'flutterwithfirebase-4a869',
    storageBucket: 'flutterwithfirebase-4a869.appspot.com',
    iosClientId: '908766428964-8mi60c0prdrhrmvm1e098hba6g0rovvd.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterwithfirebase.RunnerTests',
  );
}
